# Generated by Django 5.2.17 on 2026-08-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Remote image URL for the initial catalog; migrate to managed media in production.'),
        ),
    ]
