# Generated by Django 5.2.17 on 2026-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_product_details_and_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="Аты-жөні"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Instagram"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Қала"),
                ),
                (
                    "craft",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Қолөнер түрі"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Хабарлама")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Жаңа"),
                            ("contacted", "Байланысқа шықты"),
                            ("approved", "Қабылданды"),
                            ("rejected", "Бас тартылды"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Шебер өтінімі",
                "verbose_name_plural": "Шеберлер өтінімдері",
                "ordering": ("-created_at",),
            },
        ),
    ]
